### ISSUE TITLE
databricksにカラム追加

### ISSUE THREAD

**Issue by sgoy-suzutatsu** [kkhs/pocket-musubi-qrcode-scanner#29]
"今後の機能拡充を検討する際、実態理解のために下記ステータスごとの件数を知れると嬉しいなと思うのですが
 印刷済み | 印刷エラー｜印刷対象外                                                                                                                                                                                                "

**Comment by kkimura-kkhs** [comment]
対象リポジトリが誤っていた為このIssueはクローズ。
代替は https://github.com/kkhs/kusabi-issues/issues/1937
